# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gerald
tagline:             'therapy - poetry'
description:         'Description here . . . '
url:                 http://gerald.nz
baseurl:             http://gerald.nz
paginate:            5

# About/contact
author:
  name:              Gerald Lee Jordan
  url:               https://twitter.com/geraldleejordan
  email:             jerryleejordan@gmail.com

# Custom vars
version:             1.0.0

# Twitter plugin (added by Jerry)

twitter:
  consumer_key: asdf
  consumer_secret: asdf
  access_token: asdf
  access_token_secret: asdf
